# ruff: noqa: F401 - every site-list import here exists only to be collected into SITE_DEFINITIONS below.
from __future__ import annotations

from phoenixadult.registry.selectors.aggregators.data18empire import DATA18EMPIRE_SITES
from phoenixadult.registry.selectors.aggregators.data18movies import DATA18MOVIES_SITES
from phoenixadult.registry.selectors.aggregators.data18scenes import DATA18SCENES_SITES
from phoenixadult.registry.selectors.aggregators.javbus import JAVBUS_SITES
from phoenixadult.registry.selectors.aggregators.javdatabase import JAVDATABASE_SITES
from phoenixadult.registry.selectors.aggregators.javlibrary import JAVLIBRARY_SITES
from phoenixadult.registry.selectors.aggregators.metadataapi import METADATAAPI_SITES
from phoenixadult.registry.selectors.aggregators.project1service import PROJECT1SERVICE_SITES
from phoenixadult.registry.selectors.networks.abbywinters import ABBYWINTERS_SITES
from phoenixadult.registry.selectors.networks.adultempirecash import ADULTEMPIRECASH_SITES
from phoenixadult.registry.selectors.networks.adultprime import ADULTPRIME_SITES
from phoenixadult.registry.selectors.networks.badoinkvr import BADOINKVR_SITES
from phoenixadult.registry.selectors.networks.bang import BANG_SITES
from phoenixadult.registry.selectors.networks.bellapass import BELLAPASS_SITES
from phoenixadult.registry.selectors.networks.bellesa import BELLESA_SITES
from phoenixadult.registry.selectors.networks.blurredmedia import BLURREDMEDIA_SITES
from phoenixadult.registry.selectors.networks.caramelcash import CARAMELCASH_SITES
from phoenixadult.registry.selectors.networks.cherrypimps import CHERRYPIMPS_SITES
from phoenixadult.registry.selectors.networks.couplescinema import COUPLESCINEMA_SITES
from phoenixadult.registry.selectors.networks.czechav import CZECHAV_SITES
from phoenixadult.registry.selectors.networks.czechvr import CZECHVR_SITES
from phoenixadult.registry.selectors.networks.derangeddollars import DERANGEDDOLLARS_SITES
from phoenixadult.registry.selectors.networks.dirtyflix import DIRTYFLIX_SITES
from phoenixadult.registry.selectors.networks.dirtyharddrive import DIRTYHARDDRIVE_SITES
from phoenixadult.registry.selectors.networks.evolvedfights import EVOLVEDFIGHTS_SITES
from phoenixadult.registry.selectors.networks.fakings import FAKINGS_SITES
from phoenixadult.registry.selectors.networks.femdomempire import FEMDOMEMPIRE_SITES
from phoenixadult.registry.selectors.networks.ftv import FTV_SITES
from phoenixadult.registry.selectors.networks.fuelvirtual import FUELVIRTUAL_SITES
from phoenixadult.registry.selectors.networks.fullpornnetwork import FULLPORNNETWORK_SITES
from phoenixadult.registry.selectors.networks.gammaent import GAMMAENT_SITES
from phoenixadult.registry.selectors.networks.gammaentother import GAMMAENTOTHER_SITES
from phoenixadult.registry.selectors.networks.gasm import GASM_SITES
from phoenixadult.registry.selectors.networks.grooby import GROOBY_SITES
from phoenixadult.registry.selectors.networks.hightechvr import HIGHTECHVR_SITES
from phoenixadult.registry.selectors.networks.interracialpass import INTERRACIALPASS_SITES
from phoenixadult.registry.selectors.networks.intersec import INTERSEC_SITES
from phoenixadult.registry.selectors.networks.julesjordan import JULESJORDAN_SITES
from phoenixadult.registry.selectors.networks.karups import KARUPS_SITES
from phoenixadult.registry.selectors.networks.kellymadison import KELLYMADISON_SITES
from phoenixadult.registry.selectors.networks.killergram import KILLERGRAM_SITES
from phoenixadult.registry.selectors.networks.kink import KINK_SITES
from phoenixadult.registry.selectors.networks.littlecaprice import LITTLECAPRICE_SITES
from phoenixadult.registry.selectors.networks.loveherfilms import LOVEHERFILMS_SITES
from phoenixadult.registry.selectors.networks.metart import METART_SITES
from phoenixadult.registry.selectors.networks.missax import MISSAX_SITES
from phoenixadult.registry.selectors.networks.modelcentro import MODELCENTRO_SITES
from phoenixadult.registry.selectors.networks.naughtyamerica import NAUGHTYAMERICA_SITES
from phoenixadult.registry.selectors.networks.network5kporn import SITES_5KPORN
from phoenixadult.registry.selectors.networks.network18 import NETWORK18_SITES
from phoenixadult.registry.selectors.networks.newsensations import NEWSENSATIONS_SITES
from phoenixadult.registry.selectors.networks.newsensationsother import NEWSENSATIONSOTHER_SITES
from phoenixadult.registry.selectors.networks.nubiles import NUBILES_SITES
from phoenixadult.registry.selectors.networks.nvg import NVG_SITES
from phoenixadult.registry.selectors.networks.perfectgonzo import PERFECTGONZO_SITES
from phoenixadult.registry.selectors.networks.pervcity import PERVCITY_SITES
from phoenixadult.registry.selectors.networks.pkjmedia import PKJMEDIA_SITES
from phoenixadult.registry.selectors.networks.pornbox import PORNBOX_SITES
from phoenixadult.registry.selectors.networks.porncz import PORNCZ_SITES
from phoenixadult.registry.selectors.networks.porndoepremium import PORNDOEPREMIUM_SITES
from phoenixadult.registry.selectors.networks.pornpros import PORNPROS_SITES
from phoenixadult.registry.selectors.networks.pornworld import PORNWORLD_SITES
from phoenixadult.registry.selectors.networks.private import PRIVATE_SITES
from phoenixadult.registry.selectors.networks.puba import PUBA_SITES
from phoenixadult.registry.selectors.networks.puffy import PUFFY_SITES
from phoenixadult.registry.selectors.networks.purecfnm import PURECFNM_SITES
from phoenixadult.registry.selectors.networks.queensnake import QUEENSNAKE_SITES
from phoenixadult.registry.selectors.networks.radicalcash import RADICALCASH_SITES
from phoenixadult.registry.selectors.networks.radicalcashother import RADICALCASHOTHER_SITES
from phoenixadult.registry.selectors.networks.reptyle import REPTYLE_SITES
from phoenixadult.registry.selectors.networks.romero import ROMERO_SITES
from phoenixadult.registry.selectors.networks.scoregroup import SCOREGROUP_SITES
from phoenixadult.registry.selectors.networks.sinx import SINX_SITES
from phoenixadult.registry.selectors.networks.spizoo import SPIZOO_SITES
from phoenixadult.registry.selectors.networks.steppedup import STEPPEDUP_SITES
from phoenixadult.registry.selectors.networks.stepsecrets import STEPSECRETS_SITES
from phoenixadult.registry.selectors.networks.strike3 import STRIKE3_SITES
from phoenixadult.registry.selectors.networks.teencoreclub import TEENCORECLUB_SITES
from phoenixadult.registry.selectors.networks.teenmegaworld import TEENMEGAWORLD_SITES
from phoenixadult.registry.selectors.networks.thickcash import THICKCASH_SITES
from phoenixadult.registry.selectors.networks.thickcashother import THICKCASHOTHER_SITES
from phoenixadult.registry.selectors.networks.unzipvr import UNZIPVR_SITES
from phoenixadult.registry.selectors.networks.vip4k import VIP4K_SITES
from phoenixadult.registry.selectors.networks.vna import VNA_SITES
from phoenixadult.registry.selectors.networks.wankz import WANKZ_SITES
from phoenixadult.registry.selectors.networks.wankzvr import WANKZVR_SITES
from phoenixadult.registry.selectors.networks.wownetwork import WOWNETWORK_SITES
from phoenixadult.registry.selectors.sites.adultempire import ADULTEMPIRE_SITES
from phoenixadult.registry.selectors.sites.alluremedia import ALLUREMEDIA_SITES
from phoenixadult.registry.selectors.sites.alsangels import ALSANGELS_SITES
from phoenixadult.registry.selectors.sites.amourangels import AMOURANGELS_SITES
from phoenixadult.registry.selectors.sites.analvids import ANALVIDS_SITES
from phoenixadult.registry.selectors.sites.bamvisions import BAMVISIONS_SITES
from phoenixadult.registry.selectors.sites.belami import BELAMI_SITES
from phoenixadult.registry.selectors.sites.blackpayback import BLACKPAYBACK_SITES
from phoenixadult.registry.selectors.sites.boundhoneys import BOUNDHONEYS_SITES
from phoenixadult.registry.selectors.sites.brandnewamateurs import BRANDNEWAMATEURS_SITES
from phoenixadult.registry.selectors.sites.caribbeancom import CARIBBEANCOM_SITES
from phoenixadult.registry.selectors.sites.clips4sale import CLIPS4SALE_SITES
from phoenixadult.registry.selectors.sites.clubfilly import CLUBFILLY_SITES
from phoenixadult.registry.selectors.sites.colette import COLETTE_SITES
from phoenixadult.registry.selectors.sites.cumbizz import CUMBIZZ_SITES
from phoenixadult.registry.selectors.sites.cumlouder import CUMLOUDER_SITES
from phoenixadult.registry.selectors.sites.darkroomvr import DARKROOMVR_SITES
from phoenixadult.registry.selectors.sites.desperateamateurs import DESPERATEAMATEURS_SITES
from phoenixadult.registry.selectors.sites.dickdrainers import DICKDRAINERS_SITES
from phoenixadult.registry.selectors.sites.dorcelclub import DORCELCLUB_SITES
from phoenixadult.registry.selectors.sites.dorcelvision import DORCELVISION_SITES
from phoenixadult.registry.selectors.sites.expliciteart import EXPLICITEART_SITES
from phoenixadult.registry.selectors.sites.familytherapy import FAMILYTHERAPY_SITES
from phoenixadult.registry.selectors.sites.femjoy import FEMJOY_SITES
from phoenixadult.registry.selectors.sites.finishesthejob import FINISHESTHEJOB_SITES
from phoenixadult.registry.selectors.sites.firstanalquest import FIRSTANALQUEST_SITES
from phoenixadult.registry.selectors.sites.fittingroom import FITTINGROOM_SITES
from phoenixadult.registry.selectors.sites.fuckingawesome import FUCKINGAWESOME_SITES
from phoenixadult.registry.selectors.sites.girlsoutwest import GIRLSOUTWEST_SITES
from phoenixadult.registry.selectors.sites.girlsrimming import GIRLSRIMMING_SITES
from phoenixadult.registry.selectors.sites.heavyonhotties import HEAVYONHOTTIES_SITES
from phoenixadult.registry.selectors.sites.hegre import HEGRE_SITES
from phoenixadult.registry.selectors.sites.hollyrandall import HOLLYRANDALL_SITES
from phoenixadult.registry.selectors.sites.hologirlsvr import HOLOGIRLSVR_SITES
from phoenixadult.registry.selectors.sites.hotwifexxx import HOTWIFEXXX_SITES
from phoenixadult.registry.selectors.sites.hucows import HUCOWS_SITES
from phoenixadult.registry.selectors.sites.inthecrack import INTHECRACK_SITES
from phoenixadult.registry.selectors.sites.jacquieetmichel import JACQUIEETMICHEL_SITES
from phoenixadult.registry.selectors.sites.jesseloadsmonsterfacials import JESSELOADSMONSTERFACIALS_SITES
from phoenixadult.registry.selectors.sites.jvrporn import JVRPORN_SITES
from phoenixadult.registry.selectors.sites.kin8tengoku import KIN8TENGOKU_SITES
from phoenixadult.registry.selectors.sites.lustomic import LUSTOMIC_SITES
from phoenixadult.registry.selectors.sites.lustreality import LUSTREALITY_SITES
from phoenixadult.registry.selectors.sites.manualnfo import MANUALNFO_SITES
from phoenixadult.registry.selectors.sites.manyvids import MANYVIDS_SITES
from phoenixadult.registry.selectors.sites.meanawolf import MEANAWOLF_SITES
from phoenixadult.registry.selectors.sites.melenamariarya import MELENAMARIARYA_SITES
from phoenixadult.registry.selectors.sites.melonechallenge import MELONECHALLENGE_SITES
from phoenixadult.registry.selectors.sites.momcomesfirst import MOMCOMESFIRST_SITES
from phoenixadult.registry.selectors.sites.mompov import MOMPOV_SITES
from phoenixadult.registry.selectors.sites.mydirtyhobby import MYDIRTYHOBBY_SITES
from phoenixadult.registry.selectors.sites.penthousegold import PENTHOUSEGOLD_SITES
from phoenixadult.registry.selectors.sites.pjgirls import PJGIRLS_SITES
from phoenixadult.registry.selectors.sites.playboyplus import PLAYBOYPLUS_SITES
from phoenixadult.registry.selectors.sites.plumperpass import PLUMPERPASS_SITES
from phoenixadult.registry.selectors.sites.pornstarplatinum import PORNSTARPLATINUM_SITES
from phoenixadult.registry.selectors.sites.povr import POVR_SITES
from phoenixadult.registry.selectors.sites.putalocura import PUTALOCURA_SITES
from phoenixadult.registry.selectors.sites.realitylovers import REALITYLOVERS_SITES
from phoenixadult.registry.selectors.sites.reidmylips import REIDMYLIPS_SITES
from phoenixadult.registry.selectors.sites.screwbox import SCREWBOX_SITES
from phoenixadult.registry.selectors.sites.screwmetoo import SCREWMETOO_SITES
from phoenixadult.registry.selectors.sites.sexlikereal import SEXLIKEREAL_SITES
from phoenixadult.registry.selectors.sites.sexmex import SEXMEX_SITES
from phoenixadult.registry.selectors.sites.sicflics import SICFLICS_SITES
from phoenixadult.registry.selectors.sites.sinslife import SINSLIFE_SITES
from phoenixadult.registry.selectors.sites.stasyq import STASYQ_SITES
from phoenixadult.registry.selectors.sites.straponcum import STRAPONCUM_SITES
from phoenixadult.registry.selectors.sites.swallowbay import SWALLOWBAY_SITES
from phoenixadult.registry.selectors.sites.teenytaboo import TEENYTABOO_SITES
from phoenixadult.registry.selectors.sites.tonightsgirlfriend import TONIGHTSGIRLFRIEND_SITES
from phoenixadult.registry.selectors.sites.twotgirls import TWOTGIRLS_SITES
from phoenixadult.registry.selectors.sites.ultrafilms import ULTRAFILMS_SITES
from phoenixadult.registry.selectors.sites.vipissy import VIPISSY_SITES
from phoenixadult.registry.selectors.sites.virtualreal import VIRTUALREAL_SITES
from phoenixadult.registry.selectors.sites.virtualtaboo import VIRTUALTABOO_SITES
from phoenixadult.registry.selectors.sites.vivid import VIVID_SITES
from phoenixadult.registry.selectors.sites.vogov import VOGOV_SITES
from phoenixadult.registry.selectors.sites.vrallure import VRALLURE_SITES
from phoenixadult.registry.selectors.sites.vrlatina import VRLATINA_SITES
from phoenixadult.registry.selectors.sites.vrpfilms import VRPFILMS_SITES
from phoenixadult.registry.selectors.sites.wakeupnfuck import WAKEUPNFUCK_SITES
from phoenixadult.registry.selectors.sites.watch4beauty import WATCH4BEAUTY_SITES
from phoenixadult.registry.selectors.sites.wearehairy import WEAREHAIRY_SITES
from phoenixadult.registry.selectors.sites.woodmancastingx import WOODMANCASTINGX_SITES
from phoenixadult.registry.selectors.sites.xart import XART_SITES
from phoenixadult.registry.selectors.sites.xconfessions import XCONFESSIONS_SITES
from phoenixadult.registry.selectors.sites.xevunleashed import XEVUNLEASHED_SITES
from phoenixadult.registry.selectors.sites.xillimite import XILLIMITE_SITES
from phoenixadult.registry.selectors.sites.xsinsvr import XSINSVR_SITES
from phoenixadult.registry.selectors.sites.xvirtual import XVIRTUAL_SITES
from phoenixadult.registry.site_info import SiteInfo

SITE_DEFINITIONS: list[SiteInfo] = [
    site for _, group in sorted(globals().items()) if isinstance(group, list) and group and isinstance(group[0], SiteInfo) for site in group
]
