from __future__ import annotations

from phoenixadult.models.site_info import ContentType, SearchMethod, SiteInfo
from phoenixadult.registry.selectors._factory import Provider

PROVIDER_NAME = 'Adult Prime'
PROVIDER_BASE_URL = 'https://adultprime.com'
PROVIDER_CONTENT_TYPE: ContentType = 'sceneIdName'
PROVIDER_SEARCH_METHOD: SearchMethod = 'enhanced'
PROVIDER_SEARCH_NOTES = ''
PROVIDER_SEARCH_PATH = '/studios/search?type='

PROVIDER = Provider.from_headers(__name__)

SITES: list[SiteInfo] = [
    PROVIDER.site('4K CFNM'),
    PROVIDER.site('Adult Prime Originals'),
    PROVIDER.site('Adult Prime'),
    PROVIDER.site('BBvideo'),
    PROVIDER.site('Beauty and the Senior'),
    PROVIDER.site('Blast From the Past 18'),
    PROVIDER.site('Bondagettes'),
    PROVIDER.site('Bound Men Wanked'),
    PROVIDER.site('BrasilBimbos'),
    PROVIDER.site('Breed Bus'),
    PROVIDER.site('Club Bang Boys'),
    PROVIDER.site('Club Castings'),
    PROVIDER.site('Club Sweethearts'),
    PROVIDER.site('Cockin'),
    PROVIDER.site('Color Climax'),
    PROVIDER.site('CuckOldest'),
    PROVIDER.site('DaringSex HD'),
    PROVIDER.site('Digital Desire'),
    PROVIDER.site('Dirty Gunther'),
    PROVIDER.site('Dirty Hospital'),
    PROVIDER.site('Distorded'),
    PROVIDER.site('Elegant Raw'),
    PROVIDER.site('Evil Playgrounds'),
    PROVIDER.site('Family Screw'),
    PROVIDER.site('Fan Fuckers'),
    PROVIDER.site('Fixxxion'),
    PROVIDER.site('Fresh POV'),
    PROVIDER.site('Fucking Skinny'),
    PROVIDER.site('Gonzo 2000'),
    PROVIDER.site('Granddadz'),
    PROVIDER.site('GrandMams'),
    PROVIDER.site('GrandParentsX'),
    PROVIDER.site('Group Banged'),
    PROVIDER.site('Group Mams'),
    PROVIDER.site('Group Sex Games'),
    PROVIDER.site('Hollandsche Passie'),
    PROVIDER.site('Home Grown Europe'),
    PROVIDER.site('Interraced'),
    PROVIDER.site('Jim Slip'),
    PROVIDER.site('Laras Playground'),
    PROVIDER.site('Lets Go Bi'),
    PROVIDER.site('Mams Casting'),
    PROVIDER.site('Manalized'),
    PROVIDER.site('Manko 88'),
    PROVIDER.site('Massage Sins'),
    PROVIDER.site('Mature Van'),
    PROVIDER.site('My MILFz'),
    PROVIDER.site('My Sexy Kittens'),
    PROVIDER.site('Nylon Flix'),
    PROVIDER.site('OldieX'),
    PROVIDER.site('Peep Leak'),
    PROVIDER.site('Perfect 18'),
    PROVIDER.site('Plumperd'),
    PROVIDER.site('Pornstar Classics'),
    PROVIDER.site('Pornstars Live'),
    PROVIDER.site('Prime Lesbian'),
    PROVIDER.site('Raw Euro'),
    PROVIDER.site('Red Light Sex Trips'),
    PROVIDER.site('Retro Raw'),
    PROVIDER.site('Rodox'),
    PROVIDER.site('Salsa XXX'),
    PROVIDER.site('Sensual Heat'),
    PROVIDER.site('Shadow Slaves'),
    PROVIDER.site('Sinful Raw'),
    PROVIDER.site('Sinful Soft'),
    PROVIDER.site('Sinful XXX'),
    PROVIDER.site('Southern Sins'),
    PROVIDER.site('Submissed'),
    PROVIDER.site('Summer Sinners'),
    PROVIDER.site('Sweet Femdom'),
    PROVIDER.site('Swhores'),
    PROVIDER.site('Teenrs'),
    PROVIDER.site('The Pain Files'),
    PROVIDER.site('Tranny Bizarre'),
    PROVIDER.site('UK Flashers'),
    PROVIDER.site('Vintage Classic Porn'),
    PROVIDER.site('VR Teenrs'),
    PROVIDER.site('Young Busty'),
]
