from __future__ import annotations

from phoenixadult.registry.selectors._factory import make_site
from phoenixadult.registry.site_info import ContentType, SearchMethod, SiteInfo

PROVIDER_NAME = 'Naughty America'
PROVIDER_BASE_URL = 'https://www.naughtyamerica.com'
PROVIDER_CONTENT_TYPE: ContentType = 'sceneName'
PROVIDER_SEARCH_METHOD: SearchMethod = 'enhanced'
PROVIDER_SEARCH_NOTES = ''
PROVIDER_SEARCH_PATH = '/search?term={query}'

_NAMES = [
    '2 Chicks Same Time',
    'After School',
    'American Daydreams',
    'Anal College',
    'Asian 1 on 1',
    'Ass Masterpiece',
    'Big Cock Bully',
    'Big Cock Hero',
    'Classroom',
    'College Sugarbabes',
    'Diary of a MILF',
    'Diary of a Nanny',
    'Dirty Wives Club',
    'Fans',
    'Fast Times',
    'Fuck My Ass',
    'Housewife 1 on 1',
    'I Have a Wife',
    'Inside Naughty America',
    'LA Sluts',
    'Latin Adultery',
    'Latina Stepmom',
    'Lesbian Girl on Girl',
    'Live Gym',
    'Live Gym Cam',
    'Live Naughty MILF',
    'Live Naughty Nurse',
    'Live Naughty Secretary',
    'Live Naughty Student',
    'Live Naughty Teacher',
    'Live Party Girl',
    'MILF Sugar Babes',
    "Mom's Money",
    'Mrs. Creampie',
    "My Dad's Hot Girlfriend",
    "My Daughter's Hot Friend",
    'My First Sex Teacher',
    "My Friend's Hot Girl",
    "My Friend's Hot Mom",
    'My Girl Loves Anal',
    'My Girlfriend',
    "My Girlfriend's Busty Friend",
    'My Naughty Latin Maid',
    'My Naughty Massage',
    "My Sister's Hot Friend",
    'My Wife Is My Pornstar',
    "My Wife's Hot Friend",
    'Naughty America',
    'Naughty Athletics',
    'Naughty Bookworms',
    'Naughty Country Girls',
    'Naughty Flipside',
    'Naughty Office',
    'Naughty Rich Girls',
    'Naughty Weddings',
    'Neighbor Affair',
    'Open Family',
    'Party Girls',
    'Perfect Fucking Strangers',
    'Porn Star Experience',
    'Pornstar Wife',
    'Real Girls Now',
    'Real Pornstars VR',
    'Seduced by a Cougar',
    'Show My BF',
    'Shows',
    'Single Moms',
    'Sleazy Stepdad',
    'Slut Stepmom',
    'Slut Stepsister',
    'SoCal Coeds',
    'Spring Break',
    'Summer Vacation',
    'Super Sluts',
    'T & A',
    'Teens Love Cream',
    'The Dorm Room',
    'The Dressing Room',
    'The Gym',
    'The Office',
    'The Passenger',
    'The Spa',
    'Thundercock',
    "Tonight's Fuck",
    "Tonight's Girlfriend Classic",
    'Trophy Wives',
    'True Slut Stories',
    'Watch Your Mom',
    'Watch Your Wife',
    'Wives on Vacation',
]


def _site(name: str) -> SiteInfo:
    return make_site(
        name=name,
        provider_name=PROVIDER_NAME,
        base_url=PROVIDER_BASE_URL,
        search_path=PROVIDER_SEARCH_PATH,
        content_type=PROVIDER_CONTENT_TYPE,
        search_method=PROVIDER_SEARCH_METHOD,
        search_notes=PROVIDER_SEARCH_NOTES,
        scraper_type='naughtyamerica',
        data18_enrichment=True,
    )


NAUGHTYAMERICA_SITES: list[SiteInfo] = [_site(n) for n in _NAMES]
